source: jekyll
destination: jekyll/_site
contentful:
   spaces:
      - example: # Jekyll _data folder identifier - Required
         space: xye9wqr0fbnf        # Required
         access_token: 388e284e90e7ca07f7ed566a36029cb57111ce06858122454f5f2188837ef0da # Required
         base_path: "jekyll"
